### ISSUE TITLE
Structure of ZPK is strange when setting scriptsdir.includes

### ISSUE THREAD

**Issue by minkbear** [zend-patterns/ZendServerSDK#20]
My test case:

Case 1
scriptsdir in XML = zp_script
scriptsdir.includes in file properties = scripts/post_activate.php

Output
zp_script\scripts\post_activate.php

Expected
zp_script\post_activate.php

--------------------------------------------------------
Case 2
scriptsdir in XML = zp_script
scriptsdir.includes in file properties = zp_script/includes/globals.php

Output
zp_script\includes\globals.php

Expected
zp_script\globals.php

--------------------------------------------------------
Case 3 => Pass
scriptsdir in XML = zp_script
scriptsdir.includes in file properties = zp_script/post_activate.php

Output
zp_script\post_activate.php

Expected
zp_script\post_activate.php

--------------------------------------------------------
I think that case 1 and 2 should be pass.
Because scriptsdir.includes are the list of files or folders you want to push them into scriptsdir.

Anyways, I tested all my case with [Eclipse PDT](http://www.zend.com/en/company/community/pdt/) with GUI based and export ZPK file with the same XML and properties. The output is the same as my expected.

**Comment by boedah** [comment]
@slaff: do you know whats the reason to even set `scriptsdir` in the XML?
Because this directory is moved to a temporary location during the deployment on Zend Server (and does not even exist in the application directory).
So why would I as ZPK package creator want to customize it? All I want is to make sure all my scripts are executed and have the same structure as my in my repository.

I find it really awkward that the directory is stripped from the script paths and so the structure is changed in the zpk...
Why not simply add one setting `scriptsdir`, the whole directory is included in the ZPK and this directory is moved out of the deployed application directory during deployment?
